package it.polimi.ingsw.view.commandmessage;

public enum CommandType {
    DONE,
    GRAB_TILE,
    MOVE,
    PAY,
    RESPAWN,
    SELECT_AGGREGATE_ACTION,
    SELECT_AMMO_PAYMENT,
    SELECT_BUYING_WEAPON,
    SELECT_DISCARD_WEAPON,
    SELECT_POWER_UP,
    SELECT_POWER_UP_PAYMENT,
    SELECT_RELOADING_WEAPON,
    SELECT_SCOPE,
    SELECT_SHOOT_ACTION,
    SELECT_TARGET_PLAYER,
    SELECT_TARGET_SQUARE,
    SELECT_WEAPON,
    SELECT_WEAPON_MODE,
    SHOOT,
    USE_NEWTON,
    USE_SCOPE,
    USE_TAGBACK_GRENADE,
    USE_TELEPORT
}
